version: "3.8"

services:
  backend:
    image: docker-compose-backend
    build: ./backend
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - ./backend/db.sqlite3:/backend/db.sqlite3
      - ./backend:/backend
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: docker-compose-frontend
    build: ./frontend
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=cooper
      - POSTGRES_PASSWORD=Mysky2012**
      - POSTGRES_DB=docker_django

    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
